### ISSUE TITLE
why are true ontologies generated without distractors?

### ISSUE THREAD

**Issue by shenglih** [asaparov/prontoqa#1]
thanks for your excellent work!
comparing your `sample_real_ontology` function used to generate true ontologies to `generate_theory` function used to generate false/fictional ontologies, true ontologies have to be generated without distractors, which make the comparisons unfair. would you mind illustrating why? or how to generate the true ontologies with distractors? 
thanks a bunch!

**Comment by asaparov** [comment]
Thanks!
We focused our experiments with distractors on fictional ontologies rather than true or false ontologies, and so we simply didn't implement distractors for true ontologies. Our earlier experiments (`v1` branch) on true vs false vs fictional ontologies used more limited distractors which were implemented across all three.
