### ISSUE TITLE
infinite loop when generating false ontologies with hop greater or equal to 4

### ISSUE THREAD

**Issue by shenglih** [asaparov/prontoqa#2]

**Comment by asaparov** [comment]
This is probably due to the fact that the pool of available concepts is too small to generate such large ontologies. One way to workaround this is to simply add concepts to the lists defined at [run_experiment.py:337](https://github.com/asaparov/prontoqa/blob/main/run_experiment.py#L337), 339, and 341.

Perhaps I should add a check to see if the number of hops is too large and throw a more informative error.

Hope this helps!
